services:
  mountix:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - cargo-cache:/home/mountix/.cargo/registry
      - target-cache:/workspace/target
      - .zshrc:/root/.zshrc
      - oh-my-zsh:/root/.oh-my-zsh
      - zsh-history:/root/.history
    ports:
      - "3300:3300"
    tty: true
    stdin_open: true
    networks:
      - mountix-network

  mountix-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./migrations/data/mountix_db-mountains.json:/docker-entrypoint-initdb.d/mountix_db-mountains.json
      - ./migrations/devcontainer/migrate-in-docker.sh:/docker-entrypoint-initdb.d/migrate-in-docker.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mountix_admin
      - MONGO_INITDB_ROOT_PASSWORD=mountix_password
      - MONGO_INITDB_DATABASE=mountix_db
    networks:
      - mountix-network

volumes:
  cargo-cache:
    name: mountix-cargo-cache
  target-cache:
    name: mountix-target-cache
  oh-my-zsh:
    name: mountix-oh-my-zsh
  zsh-history:
    name: mountix-zsh-history
  mongo-data:
    name: mountix-mongo-data

networks:
  mountix-network:
    driver: bridge
