[package]
name = "mountix-kernel"
version = "1.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
regex = "1.11.1"

[dev-dependencies]
tokio-test = "0.4.4"
