[package]
name = "mountix-kernel"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
